# Generated by Django 5.0.6 on 2024-09-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0009_remove_treinados_nome_remove_treinados_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='atividade_registro',
        ),
        migrations.RemoveField(
            model_name='parcerias',
            name='tis',
        ),
        migrations.CreateModel(
            name='AtividadeRegistroParcerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcerias', models.PositiveIntegerField(default=0, editable=False)),
                ('atividade_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro')),
                ('parcerias', models.ManyToManyField(related_name='atividades', to='ieb.parcerias')),
            ],
        ),
    ]
